#!/bin/sh
#/bin/mount -n -t ramfs ramfs /tmp

exec /sbin/init
~                                                                                              
~                                              
