#
# Makefile for the kernel character misc device drivers.
#
#obj-$(CONFIG_KORAIL_COMBINE_KERNEL)		+= korail_hwid.o korail_dip.o korail_tcolor_led.o korail_buzzer.o korail_fnd.o korail_sim.o korail_keys.o korail_gateio.o korail_rs485_flowcontrol.o rc531/ korail_rtc_nvram.o korail_ttlio.o
obj-$(CONFIG_KORAIL_COMBINE_KERNEL)		+= korail_hwid.o korail_dip.o korail_tcolor_led.o korail_buzzer.o korail_fnd.o korail_sim.o korail_keys.o korail_gateio.o korail_rs485_flowcontrol.o rc531/ korail_ttlio.o
obj-$(CONFIG_KORAIL_DEVICE_HWID)		+= korail_hwid.o
obj-$(CONFIG_KORAIL_DEVICE_DIPSWITCH)	+= korail_dip.o
obj-$(CONFIG_KORAIL_DEVICE_TCOLOR_LED)	+= korail_tcolor_led.o
obj-$(CONFIG_KORAIL_DEVICE_BUZZER)		+= korail_buzzer.o
obj-$(CONFIG_KORAIL_DEVICE_FND)			+= korail_fnd.o
obj-$(CONFIG_KORAIL_DEVICE_SIM)			+= korail_sim.o
obj-$(CONFIG_KORAIL_DEVICE_KEYS)		+= korail_keys.o
obj-$(CONFIG_KORAIL_DEVICE_GATE_IO)		+= korail_gateio.o
obj-$(CONFIG_KORAIL_DEVICE_RS485)		+= korail_rs485_flowcontrol.o
obj-$(CONFIG_KORAIL_DEVICE_RC531)		+= rc531/
#obj-$(CONFIG_KORAIL_DEVICE_DS1338)		+= korail_rtc_nvram.o
obj-$(CONFIG_KORAIL_DEVICE_TTLIO)		+= korail_ttlio.o
